name: MineralContest
main: com.pl4giat.mineralcontest.Main
version: 1.0
commands:
  mcontest:
    usage: /mcontest [args]
    description: All the Mineral Contest setup commands
  arena:
    usage: /arena
    description: Teleport to the Arena